/**
 * Constantes relacionadas con Paraguay para checkout y formularios
 */

export const PARAGUAY_DEPARTMENTS = [
  'Asunción',
  'Alto Paraguay',
  'Alto Paraná',
  'Amambay',
  'Boquerón',
  'Caaguazú',
  'Caazapá',
  'Canindeyú',
  'Central',
  'Concepción',
  'Cordillera',
  'Guairá',
  'Itapúa',
  'Misiones',
  'Ñeembucú',
  'Paraguarí',
  'Presidente Hayes',
  'San Pedro',
] as const;

export type ParaguayDepartment = (typeof PARAGUAY_DEPARTMENTS)[number];

export const PARAGUAY_CITIES: Record<ParaguayDepartment, string[]> = {
  'Asunción': [
    'Asunción',
  ],
  'Alto Paraguay': [
    'Fuerte Olimpo',
    'Mayor Pablo Lagerenza',
  ],
  'Alto Paraná': [
    'Ciudad del Este',
    'Hernandarias',
    'Presidente Franco',
    'San Alberto',
    'San Cristóbal',
  ],
  'Amambay': [
    'Pedro Juan Caballero',
    'Bella Vista',
    'Capitán Bado',
  ],
  'Boquerón': [
    'Filadelfia',
    'Loma Plata',
    'Mariscal Estigarribia',
  ],
  'Caaguazú': [
    'Coronel Oviedo',
    'Caaguazú',
    'Carayaó',
    'Dr. J. Eulogio Estigarribia',
    'Dr. Juan Manuel Frutos',
    'José Domingo Ocampos',
    'La Pastora',
    'Mcal. Francisco Solano López',
    'Nueva Londres',
    'R.I. 3 Corrales',
    'Repatriación',
    'R. I. 3 Corrales',
    'San José de los Arroyos',
    'San Joaquín',
    'Yhú',
  ],
  'Caazapá': [
    'Caazapá',
    'Abaí',
    'Buena Vista',
    'Dr. Moisés S. Bertoni',
    'General Higinio Morínigo',
    'Maciel',
    'San Juan Nepomuceno',
    'Tavaí',
    'Yuty',
  ],
  'Canindeyú': [
    'Salto del Guairá',
    'Corpus Christi',
    'Curuguaty',
    'General Francisco Caballero Álvarez',
    'Itanará',
    'Katueté',
    'La Paloma del Espíritu Santo',
    'Nueva Esperanza',
    'Ygatimí',
    'Yby Pytã',
    'Ybyrarovaná',
    'Ypejhú',
  ],
  'Central': [
    'Areguá',
    'Capiatá',
    'Fernando de la Mora',
    'Guarambaré',
    'Itá',
    'Itauguá',
    'Julián Augusto Saldívar',
    'Lambaré',
    'Limpio',
    'Luque',
    'Mariano Roque Alonso',
    'Ñemby',
    'Nueva Italia',
    'San Antonio',
    'San Lorenzo',
    'Villa Elisa',
    'Villeta',
    'Ypacaraí',
    'Ypané',
  ],
  'Concepción': [
    'Concepción',
    'Azotey',
    'Belén',
    'Horqueta',
    'Loreto',
    'San Carlos del Apa',
    'San Lázaro',
    'Sargento José Félix López',
    'Yby Yaú',
  ],
  'Cordillera': [
    'Caacupé',
    'Altos',
    'Arroyos y Esteros',
    'Atyrá',
    'Caraguatay',
    'Emboscada',
    'Eusebio Ayala',
    'Isla Pucú',
    'Itacurubí de la Cordillera',
    'Juan de Mena',
    'Loma Grande',
    'Mbocayaty del Yhaguy',
    'Nueva Colombia',
    'Piribebuy',
    'Primero de Marzo',
    'San Bernardino',
    'Santa Elena',
    'Tobatí',
    'Valenzuela',
  ],
  'Guairá': [
    'Villarrica',
    'Borja',
    'Capitán Mauricio José Troche',
    'Coronel Martínez',
    'Dr. Bottrell',
    'Félix Pérez Cardozo',
    'General Eugenio A. Garay',
    'Independencia',
    'Itapé',
    'Iturbe',
    'José Fassardi',
    'Mbocayaty',
    'Natalicio Talavera',
    'Ñumí',
    'Paso Yobái',
    'San Salvador',
  ],
  'Itapúa': [
    'Encarnación',
    'Bella Vista',
    'Cambyretá',
    'Capitán Meza',
    'Capitán Miranda',
    'Carlos Antonio López',
    'Carmen del Paraná',
    'Coronel Bogado',
    'Edelira',
    'Fram',
    'General Artigas',
    'General Delgado',
    'Hohenau',
    'Jesús',
    'José Leandro Oviedo',
    'La Paz',
    'Leandro N. Alem',
    'Mayor Otaño',
    'Natalio',
    'Nueva Alborada',
    'Obligado',
    'Pirapó',
    'San Cosme y Damián',
    'San Juan del Paraná',
    'San Pedro del Paraná',
    'San Rafael del Paraná',
    'Tomás Romero Pereira',
    'Trinidad',
    'Yatytay',
  ],
  'Misiones': [
    'San Juan Bautista',
    'Ayolas',
    'San Ignacio',
    'San Miguel',
    'San Patricio',
    'Santa María',
    'Santa Rosa',
    'Santiago',
    'Villa Florida',
    'Yabebyry',
  ],
  'Ñeembucú': [
    'Pilar',
    'Alberdi',
    'Cerrito',
    'Desmochados',
    'General José Eduvigis Díaz',
    'Guazú Cuá',
    'Humaitá',
    'Isla Umbú',
    'Laureles',
    'Mayor José J. Martínez',
    'Paso de Patria',
    'San Juan Bautista del Ñeembucú',
    'Tacuaras',
    'Villa Franca',
    'Villa Oliva',
    'Villalbín',
  ],
  'Paraguarí': [
    'Paraguarí',
    'Acahay',
    'Caapucú',
    'Carapeguá',
    'Escobar',
    'General Bernardino Caballero',
    'La Colmena',
    'Mbuyapey',
    'Pirayú',
    'Quiindy',
    'Quyquyhó',
    'San Roque González de Santa Cruz',
    'Sapucai',
    'Tebicuary-mí',
    'Yaguarón',
    'Ybycuí',
    'Ybytymí',
  ],
  'Presidente Hayes': [
    'Villa Hayes',
    'Benjamín Aceval',
    'José Falcón',
    'Nanawa',
    'Puerto Pinasco',
    'Teniente Irala Fernández',
  ],
  'San Pedro': [
    'San Pedro de Ycuamandiyú',
    '25 de Diciembre',
    'Antequera',
    'Capiibary',
    'Choré',
    'General Elizardo Aquino',
    'General Isidoro Resquín',
    'Guayaibí',
    'Itacurubí del Rosario',
    'Lima',
    'Nueva Germania',
    'San Estanislao',
    'San Pablo',
    'Santa Rosa del Aguaray',
    'Tacuatí',
    'Unión',
    'Villa del Rosario',
    'Yataity del Norte',
    'Yrybucuá',
  ],
};

/**
 * Validación de teléfono paraguayo
 * Formato: 0981234567 (10 dígitos, empezando con 09)
 */
export function isValidParaguayPhone(phone: string): boolean {
  const cleaned = phone.replace(/\s+/g, '');
  return /^09\d{8}$/.test(cleaned);
}

/**
 * Formatea teléfono paraguayo para mostrar
 * Ejemplo: 0981234567 -> 0981 234 567
 */
export function formatParaguayPhone(phone: string): string {
  const cleaned = phone.replace(/\s+/g, '');
  if (cleaned.length === 10) {
    return `${cleaned.slice(0, 4)} ${cleaned.slice(4, 7)} ${cleaned.slice(7)}`;
  }
  return phone;
}

/**
 * Costos de envío por departamento (en Guaraníes)
 */
export const SHIPPING_COSTS: Record<ParaguayDepartment, number> = {
  'Asunción': 20000,
  'Central': 20000,
  'Alto Paraguay': 50000,
  'Alto Paraná': 50000,
  'Amambay': 50000,
  'Boquerón': 50000,
  'Caaguazú': 50000,
  'Caazapá': 50000,
  'Canindeyú': 50000,
  'Concepción': 50000,
  'Cordillera': 50000,
  'Guairá': 50000,
  'Itapúa': 50000,
  'Misiones': 50000,
  'Ñeembucú': 50000,
  'Paraguarí': 50000,
  'Presidente Hayes': 50000,
  'San Pedro': 50000,
};

/**
 * Número mínimo de items para envío gratis
 */
export const FREE_SHIPPING_MIN_ITEMS = 3;

